trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name: solution
    value: '**/*.sln'
  - name : buildPlatform 
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release' 
  - template: global-variables-shared.yml
  

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script:  "echo ${{ variables.solution }}"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My shared secret is '$(va)'!"