trigger:
- master

pool:
  vmImage: 'windows-latest'

- template: global-variables-shared.yml

variables:
  
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
    
  

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script:  "echo ${{ variables.solution }}"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My secret is '$(secretvalue)'!"
    - script: "echo My shared secret is '$(va)'!"